{
    "openapi": "3.0.0",
    "info": {
        "title": "api-project-fullstack-juorlando",
        "description": "API para utilização no projeto full stack da sprint 2 do M6 da Kenzie Academy. Tem como finalidade a criação de usuários e suas opções de contado, o CRUD completo de cada rota e suas interações.",
        "termsOfService": "",
        "contact": {
            "email": "juniororlandocv@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/",
            "description": "API do projeto"
        }
    ],
    "paths": {
        "/users": {
            "post": {
                "summary": "Cadastro de usuário",
                "description": "rota responsável por cadastrar um usuário",
                "tags": ["users"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "Teste",
                                        "email": "teste@mail.com",
                                        "password": "123456",
                                        "phone": "11942254688"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Email already exists"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "name": "teste2",
                                        "email": "teste2@mail.com",
                                        "phone": "11942254682",
                                        "id": 2,
                                        "created_at": "2023-06-04"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "listagem de usuários",
                "description": "rota responsavel por listar todos os usuários",
                "tags": ["users"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "example": {
                                        "name": "teste2",
                                        "email": "teste2@mail.com",
                                        "phone": "11942254682",
                                        "id": 2,
                                        "created_at": "2023-06-04"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "patch": {
                "summary": "atualização dos dados do usuário",
                "description": "rota responsável por atualizar dos dados do usuário",
                "tags": ["users"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "user id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "Teste",
                                        "email": "teste@mail.com",
                                        "password": "123456",
                                        "phone": "11942254688"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404": {
                        "description": "User not found"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Email already exists"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/users"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "deleção de usuário",
                "description": "rota responsável por apagar o usuário do banco de dados",
                "tags": ["users"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "user id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {}
                },
                "responses": {
                    "404": {
                        "description": "User not found"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "204": {
                        "description": "no content"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "summary": "login de usuario",
                "description": "rota responsável por fazer o login de usuário",
                "tags": ["login"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/login"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "email": "teste@mail.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImxhdXJpbmhhIiwiaWF0IjoxNjg1OTYxNDM1LCJleHAiOjE2ODU5NjUwMzUsInN1YiI6IjE0In0.ne1e9Ewi8u0sgfYSEWIsO9xCqEnyqKWyi6SDFI2AJgk"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Invalid credentials"
                    }
                }
            }
        },
        "contacts": {
            "post": {
                "summary": "criação de contato",
                "description": "rota responsavel por criar um contato relacionado ao usuário",
                "tags": ["contacts"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/contacts"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "teste",
                                        "email": "teste@mail.com",
                                        "password": "123456",
                                        "phone": "123213214"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Email already exists"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "name": "teste2",
                                        "email": "teste2@mail.com",
                                        "phone": "11942254682",
                                        "id": 2,
                                        "created_at": "2023-06-04"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "listagem de contatos",
                "description": "rota responsavel por listar todos os contatos",
                "tags": ["contacts"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "example": {
                                        "name": "teste2",
                                        "email": "teste2@mail.com",
                                        "phone": "11942254682",
                                        "id": 2,
                                        "created_at": "2023-06-04"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "contacts/{id}": {
            "patch": {
                "summary": "atualização dos dados de contato",
                "description": "rota responsável pela atualização dos dados do contato",
                "tags": ["contacts"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "contact id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/contacts"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "Teste",
                                        "email": "teste@mail.com",
                                        "password": "123456",
                                        "phone": "11942254688"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404": {
                        "description": "Contact not found"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Email already exists"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/contacts"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "deleção de contato",
                "description": "rota responsável por apagar o contato do banco de dados",
                "tags": ["contacts"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "contact id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {}
                },
                "responses": {
                    "404": {
                        "description": "Contact not found"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "204": {
                        "description": "no content"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "users": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    },
                    "created_at": {
                        "type": "string"
                    }
                }
            },
            "login": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "contacts": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "userId": {
                        "type": "number"
                    },
                    "id": {
                        "type": "number"
                    },
                    "created_at": {
                        "type": "string"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}